---
apiVersion: v1
kind: Namespace
metadata:
  name: flask
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: python:3.9.16-slim
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: mysql_db_endpoint
              value: mysql-service.mysql.svc.cluster.local
            - name: mysql_db_username
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: mysql_db_username
            - name: mysql_db_password
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: mysql_db_password
            - name: mysql_db_database
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: mysql_db_database
            - name: sendgrid_api_key
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: sendgrid_api_key
            - name: sendgrid_sender_email
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: sendgrid_sender_email
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask
